// Package enrichers defines what an enricher is: something that annotates a
// graph with facts a parser could not know.
//
// The pipeline is parsers -> IR -> enrichers -> renderers, and the boundary
// between the middle two is the one hard rule about who writes what. An
// enricher may write Node.Coverage, Node.Metrics, Node.Claim, Edge.Claim,
// Edge.Suppressed and Graph.Conflicts, and may add nodes and edges. It must
// never touch Node.Attrs, which belongs to parsers.
//
// Enrichers are wired explicitly rather than registering themselves. A
// provider Profile is pure data looked up by prefix from code that must not
// import it, which is why that package has a registry; an enricher is
// behaviour with its own input file and its own flags, so the command line has
// to name it anyway. A registry would buy dynamic dispatch nothing calls, and
// would add init-order coupling to every binary that imported one. The
// interface is defined here so that a registry, if it is ever wanted, is a
// small addition rather than a rewrite.
package enrichers

import (
	"fmt"
	"io"
	"sort"
	"strings"

	"github.com/imohiyoko/oekaki/core"
)

// An Enricher annotates a graph in place.
type Enricher interface {
	// Name is the short name used in reports and error messages.
	Name() string

	// Enrich annotates g and returns what it could not resolve.
	//
	// A non-empty report is not an error. Partial evidence is the normal
	// case — somebody looked at some of the estate, not all of it — and the
	// report exists so that the part which did not land is visible rather
	// than dropped. An error means the enricher could not run at all.
	Enrich(g *core.Graph) (*Report, error)
}

// Unmatched is a selector that named nothing in the graph.
type Unmatched struct {
	Selector map[string]string `json:"selector"`
	Assert   string            `json:"assert"`
	Reason   string            `json:"reason"`

	// Action is what was done about it: "adopted" or "dropped".
	Action string `json:"action"`
}

// Ambiguous is a selector that named more than one thing.
type Ambiguous struct {
	Selector   map[string]string `json:"selector"`
	Assert     string            `json:"assert"`
	Candidates []string          `json:"candidates"`
}

// Report is what an enricher could not do, and what it did instead.
//
// It is not an error type. It exists because the alternative to reporting is
// dropping, and evidence dropped without a word is how a coverage map ends up
// confidently wrong: a diagram missing a finding looks exactly like a diagram
// with nothing to find.
type Report struct {
	Enricher  string         `json:"enricher"`
	Applied   int            `json:"applied"`
	Coverage  map[string]int `json:"coverage,omitempty"`
	Unmatched []Unmatched    `json:"unmatched,omitempty"`
	Ambiguous []Ambiguous    `json:"ambiguous,omitempty"`
	Adopted   []string       `json:"adopted,omitempty"`
	Conflicts int            `json:"conflicts"`

	// Window is the period the overlay's author says their evidence covers,
	// echoed so the summary can say what the numbers are about.
	Window string `json:"window,omitempty"`

	// Sources names the overlay files applied, for the same reason.
	Sources []string `json:"sources,omitempty"`
}

// Clean reports whether everything resolved.
func (r *Report) Clean() bool { return len(r.Unmatched) == 0 && len(r.Ambiguous) == 0 }

// Sort puts the report in a canonical order.
//
// Load-bearing rather than tidy: the report is written to a file that is
// regenerated by `make example` and checked by CI, so an unsorted map
// iteration here would make the determinism gate flaky — and a flaky
// determinism gate is worse than no gate.
func (r *Report) Sort() {
	sort.SliceStable(r.Unmatched, func(i, j int) bool {
		return selectorString(r.Unmatched[i].Selector) < selectorString(r.Unmatched[j].Selector)
	})
	sort.SliceStable(r.Ambiguous, func(i, j int) bool {
		return selectorString(r.Ambiguous[i].Selector) < selectorString(r.Ambiguous[j].Selector)
	})
	for i := range r.Ambiguous {
		sort.Strings(r.Ambiguous[i].Candidates)
	}
	sort.Strings(r.Adopted)
}

// WriteText writes the human summary.
//
// Printed on every run, not only when something went wrong. A summary that
// appears only on failure teaches people to read its absence as success, and
// the interesting number here — how much of the estate nobody has assessed —
// is not a failure.
func (r *Report) WriteText(w io.Writer) {
	name := r.Enricher
	if name == "" {
		name = "enricher"
	}

	head := fmt.Sprintf("%s: %d assertions applied", name, r.Applied)
	if len(r.Sources) > 0 {
		head = fmt.Sprintf("%s: %d %s, %d assertions applied",
			name, len(r.Sources), plural(len(r.Sources), "file", "files"), r.Applied)
	}
	fmt.Fprintln(w, head)

	if len(r.Coverage) > 0 {
		line := "  coverage: " + coverageSummary(r.Coverage)
		if r.Window != "" {
			line += fmt.Sprintf("  (window: %s)", r.Window)
		}
		fmt.Fprintln(w, line)
	}

	for _, u := range r.Unmatched {
		fmt.Fprintf(w, "  matched nothing (%s): %s\n", u.Action, selectorString(u.Selector))
	}
	for _, a := range r.Ambiguous {
		fmt.Fprintf(w, "  ambiguous, not applied: %s -> %s\n",
			selectorString(a.Selector), strings.Join(a.Candidates, ", "))
	}
	if r.Conflicts > 0 {
		fmt.Fprintf(w, "  %d %s recorded\n", r.Conflicts, plural(r.Conflicts, "conflict", "conflicts"))
	}
}

// coverageOrder is the order states are summarised in: the ones worth acting
// on first, and "unknown" last because it is a measure of what has not been
// looked at rather than of what is wrong.
var coverageOrder = []string{"blind", "silent", "undeclared", "flowing", "unknown"}

func coverageSummary(counts map[string]int) string {
	var parts []string
	for _, state := range coverageOrder {
		if n, ok := counts[state]; ok {
			parts = append(parts, fmt.Sprintf("%d %s", n, state))
		}
	}
	// Anything the list above does not know about still has to appear, or a
	// new state would vanish from the summary until somebody noticed.
	var extra []string
	for state := range counts {
		known := false
		for _, s := range coverageOrder {
			if s == state {
				known = true
			}
		}
		if !known {
			extra = append(extra, fmt.Sprintf("%d %s", counts[state], state))
		}
	}
	sort.Strings(extra)
	return strings.Join(append(parts, extra...), ", ")
}

func selectorString(s map[string]string) string {
	keys := make([]string, 0, len(s))
	for k := range s {
		keys = append(keys, k)
	}
	sort.Strings(keys)

	var parts []string
	for _, k := range keys {
		parts = append(parts, fmt.Sprintf("%s=%s", k, s[k]))
	}
	return "{" + strings.Join(parts, " ") + "}"
}

func plural(n int, one, many string) string {
	if n == 1 {
		return one
	}
	return many
}
